#!/usr/bin/env sh
# direnvsh - Load .envrc files into shell from parent directories
# Copyright (C) 2022  Peter Willis
# shellcheck disable=SC1090,SC2016,SC2003

DIRENVSH_VER="0.1"
set -eu ; [ "${DEBUG:-0}" = "1" ] && set -x

_rloadfiles () {
    file="$1"
    trap _cleanup_tmp EXIT
    if [ "${DIRENVSH_EXPORT_MODE}" = "1" ] ; then
        tmpfile="$(mktemp "$TMPDIR/direnvsh.XXXXXXXXXX")"
    fi
    direnvsh_cwd="$(pwd)"
    set -a # export all variables set after here
    direnvsh_level=0
    while : ; do
        if [ -e "$direnvsh_cwd/.stopdirenvshrc" ] || [ "${DIRENVSH_STOP:-0}" = "1" ] ; then
            printf "%s: Stopping processing envrc files\n" "$0" 1>&2
            break
        fi
        if [ -e "$direnvsh_cwd/$file" ] ; then
            printf "%s: Loading envrc '%s'\n" "$0" "$direnvsh_cwd/$file" 1>&2
            if [ "${DIRENVSH_EXPORT_MODE}" = "1" ] ; then
                env -i sh -c "unset SHLVL PWD; set -a; . \"$direnvsh_cwd/$file\"; export -p" >> "$tmpfile"
            elif [ "${DIRENVSH_DYNAMIC_MODE}" = "1" ] ; then
                . "$direnvsh_cwd/$file"
            elif [ "${DIRENVSH_SIMPLE_MODE}" = "1" ] ; then
                _readkv < "$direnvsh_cwd/$file"
            fi
        fi
        direnvsh_level=$((direnvsh_level+1))
        direnvsh_cwd="$(dirname "$direnvsh_cwd")"
        [ "$direnvsh_cwd" = "/" ] && break
    done
    if [ "${DIRENVSH_EXPORT_MODE}" = "1" ] ; then
        . "$tmpfile"
        rm -f "$tmpfile"
    fi
}
_readkv () {
    while IFS='=' read -r key val; do
        # Skip comments
        [ "${key##\#*}" ] || continue
        printf "%s: Found k/v '%s=%s'\n" "$0" "$key" "$val" 1>&2
        set +e
        # Replace text '${FOO}' with value of '$FOO'
        _replaceval_ind "$key" "$val" '^.*${[a-zA-Z0-9_]\+}' '^.*${\([a-zA-Z0-9_]\+\)}.*$'
        # Replace text '$FOO' with value of '$FOO'
        _replaceval_ind "$key" "$val" '^.*$[a-zA-Z0-9_]\+' '^.*$\([a-zA-Z0-9_]\+\).*$'
        set -e
    done
}
_replaceval_ind () {
    _k="$1" _v="$2" _idxregex="$3" _regex="$4" _matchidx='' _match='' _new='' _idx='' _begin='' _end=''
    while : ; do
        _matchidx="$(expr "$_v" : "$_idxregex")"
        if [ ! "$_matchidx" = "0" ] ; then
            _match="$(expr "$_v" : "$_regex")"
            eval _new="\${$_match:-}"
            _idx=$((_matchidx-(${#_match}+1)))
            _begin="$(expr substr "$_v" 1 $_idx)"
            _end="$(expr substr "$_v" $((_matchidx+1)) 99999999)"
            _v="${_begin}${_new}${_end}"
            export "$_k=$_v"
        else
            export "$_k=$_v"
            break
        fi
    done
}
_cleanup_tmp () {
    if [ "${NO_CLEANUP_TMP_ON_ERROR:-0}" = "1" ] ; then
        printf "%s: Error detected; not cleaning up '%s'\n" "$0" "${tmpfile:-}" 1>&2
    else
        if [ "${NO_CLEANUP_TMP:-0}" = "1" ] ; then
            printf "%s: Not cleaning up '%s'\n" "$0" "${tmpfile:-}" 1>&2
        elif [ -n "${tmpfile:-}" ] ; then
            rm -f "$tmpfile"
        fi
    fi
}
_direnvsh_help () {
    echo "Usage: $0 [OPTIONS] [--] [COMMAND ..]"
    echo ""
    echo "Loads a .envrc file from current and parent directories into the shell."
    echo "If COMMAND and any arguments are passed, they are executed."
    echo ""
    echo "Options:"
    echo "  -S          Simple mode (default): only parse files with line-by-line KEY=VALUE entries"
    echo "              instead of loading the file into the shell. Interpolates environment variables."
    echo "              The ENVRC is set to .env unless otherwise specified."
    echo ""
    echo "  -D          Dynamic mode: load each file into the shell session immediately."
    echo "              The ENVRC is set to .envrc unless otherwise specified."
    echo ""
    echo "  -E          Export mode: use a subshell to export each .envrc and only load values"
    echo "              into the shell after all exported variables are concatenated."
    echo "              The ENVRC is set to .envrc unless otherwise specified."
    echo ""
    echo "  -f ENVRC    Load files named ENVRC rather than '.envrc'"
    echo "  -h          This screen"
    echo "  -v          Enable debug mode (DEBUG=1)"
    echo "  -V          Version of direnvsh"
    exit 1
}

DIRENVSH_SHOW_HELP=0
DIRENVSH_SIMPLE_MODE="${DIRENVSH_SIMPLE_MODE:-1}"
DIRENVSH_DYNAMIC_MODE="${DIRENVSH_DYNAMIC_MODE:-0}"
DIRENVSH_EXPORT_MODE="${DIRENVSH_EXPORT_MODE:-0}"
TMPDIR="${TMPDIR:-/tmp}" # POSIX standard temp dir

while getopts "SDEf:hvV" args ; do
    case $args in
        S)  
            DIRENVSH_SIMPLE_MODE=1 DIRENVSH_DYNAMIC_MODE=0 DIRENVSH_EXPORT_MODE=0 ;;
        D)  
            DIRENVSH_SIMPLE_MODE=0 DIRENVSH_DYNAMIC_MODE=1 DIRENVSH_EXPORT_MODE=0 ;;
        E)  
            DIRENVSH_SIMPLE_MODE=0 DIRENVSH_DYNAMIC_MODE=0 DIRENVSH_EXPORT_MODE=1 ;;
        f)  
            ENVRC="$OPTARG" ;;
        h)  
            DIRENVSH_SHOW_HELP=1 ;;
        v)  
            DEBUG=1 ;;
        V)  
            printf "%s\n" "$DIRENVSH_VER" ; exit 0 ;;
        *)  
            printf "%s: Error: unknown option '%s'\n" "$0" "$args" 1>&2 ; _direnvsh_help ;;
    esac
done
shift $((OPTIND-1))

[ "${DIRENVSH_SHOW_HELP}" = "1" ] && _direnvsh_help
[ "${DEBUG:-0}" = "1" ] && set -x

[ "${DIRENVSH_SIMPLE_MODE}" = "1" ] && ENVRC="${ENVRC:-.env}"
[ "${DIRENVSH_DYNAMIC_MODE}" = "1" ] && ENVRC="${ENVRC:-.envrc}"
[ "${DIRENVSH_EXPORT_MODE}" = "1" ] && ENVRC="${ENVRC:-.envrc}"

_rloadfiles "$ENVRC"

# If there were command-line options left, execute them
[ $# -lt 1 ] || exec "$@"
